
# Map the URL path /sysmon to the CGI script
ScriptAlias /wifi "/srv/programs/wifi_configuration/flask_cgi_backend.exec.py"

# Provide permissions and enable CGI execution for the CGI script directory
<Directory /srv/programs/wifi_configuration>
  Options +FollowSymlinks +ExecCGI
  AllowOverride All
  AddHandler cgi-script .py
  Require all granted
  DirectoryIndex flask_cgi_backend.exec.py
</Directory>

# Logging configuration for errors for the /sysmon alias
#ErrorLog ${APACHE_LOG_DIR}/wifi_error.log
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

