
# Map the URL path /sysmon to the CGI script
ScriptAlias /sysmon "/srv/programs/sys_monitor_http/flask_cgi_backend.py"

# Provide permissions and enable CGI execution for the CGI script directory
<Directory /srv/programs/sys_monitor_http>
  Options +FollowSymlinks +ExecCGI
  AllowOverride All
  AddHandler cgi-script .py
  Require all granted
  DirectoryIndex flask_cgi_backend.py
</Directory>

# Map /sysmon/static to the static files directory
#Alias /sysmon/static "/srv/programs/sys_monitor_http/static"

# Provide permissions for serving static files without CGI execution
#<Directory "/srv/programs/sys_monitor_http/static">
#    Options +FollowSymLinks
#    AllowOverride All
#    Require all granted
#</Directory>

# Logging configuration for monitoring access and errors for the /sysmon alias
ErrorLog ${APACHE_LOG_DIR}/sysmon_error.log
# CustomLog ${APACHE_LOG_DIR}/sysmon_access.log combined
# ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

