Alias /sysmon "/srv/programs/sys_monitor_http"

<Directory /srv/programs/sys_monitor_http>
  Options +FollowSymlinks
  AllowOverride All

  Options +ExecCGI
  AddHandler cgi-script .py
  Require all granted

  ScriptAlias / /path/to/your/system_monitor/flask_cgi_backend.py/

  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined

</Directory>
